coffeeshop/urls.py
from django.urls import path

from . import views

app_name = 'coffeeshop'
urlpatterns = [
    path('', views.OrderCreateView.as_view(), name='index'),
    path('ajax/load-drinktypes/', views.load_drinktypes, name='ajax_load_drinktypes'),
    path('ajax/load-sizes/', views.load_sizes, name='ajax_load_sizes'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-list/', views.OrderListView.as_view(), name = 'order_list'),
    path('filtered-order-list/', views.FilteredOrderListView.as_view(), name = 'filtered_order_list'),
]

wwarkop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coffeeshop/', include('coffeeshop.urls')),
]

admin.site.site_header = "W-Warkop"
admin.site.site_title = "Website Warkop"
admin.site.index_title = "Welcome to W-Warkop"

coffeeshop/models.py
import datetime

from django.db import models
from django.db.models import Sum, F
from django.utils import timezone

# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=20, unique=True)
	def __str__(self):
		return self.name

class DrinkType(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=20, unique=True)
    def __str__(self):
        return self.name

class Size(models.Model):
    name = models.CharField(max_length=20, unique=True)
    def __str__(self):
        return self.name

class Drink(models.Model):
    price = models.PositiveIntegerField(default=0)
    drink_type = models.ForeignKey(DrinkType, on_delete=models.PROTECT)
    size = models.ForeignKey(Size, on_delete=models.PROTECT)
    class Meta:
        unique_together = ('drink_type', 'size')

    def __str__(self):
        # return self.drink_type.name + "_" + self.size.name
        return f'{self.drink_type}| {self.price} {self.size.name}'

#        return repr(dict(id=self.id, drink_type=self.drink_type.name,
#            size=self.size.name, price=self.price))

class Order(models.Model):
    customer = models.CharField(max_length=100, verbose_name="Name Customer")
    quantity = models.IntegerField()
    drink = models.ForeignKey(Drink, on_delete=models.PROTECT)
    ordered_at = models.DateTimeField('order_timestamp')
    def __str__(self):
        return self.customer

#       return repr(dict(id=self.id, quantity=self.quantity,
#           drink=self.drink.drink_type.name))

    @classmethod
    def total_sales(self):
        return Order.objects.aggregate(total=Sum(F('drink__price') * F('quantity'),
            output_field=models.DecimalField(decimal_places=2)))['total']

coffeeshop/forms.py
from django import forms
from .models import Category, DrinkType, Size

class OrderForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Select")
    drink_type = forms.ModelChoiceField(queryset=DrinkType.objects.none(), empty_label="Select")
    size = forms.ModelChoiceField(queryset=Size.objects.none(), empty_label="Select")
    quantity = forms.IntegerField(min_value = 1)


class FilterForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="All", required=False)
    size = forms.ModelChoiceField(queryset=Size.objects.all(), empty_label="All", required=False)

coffeeshop/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import DrinkType, Drink, Order
from .forms import OrderForm, FilterForm

class OrderListView(generic.ListView, generic.FormView):
    template_name = 'coffeeshop/order_list.html'
    context_object_name = 'order_list'
    form_class = FilterForm

    def get_queryset(self):
        # return Order.objects.all().order_by('id')[:20]
        return Order.objects.all().order_by('id')
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(OrderListView, self).get_context_data(**kwargs)
        # Add in total sales
        context['total_sales'] = Order.total_sales()
        return context

class FilteredOrderListView(generic.ListView):
    template_name = 'coffeeshop/filtered_order_list.html'
    context_object_name = 'order_list'

    def get_queryset(self):
        category_id = self.request.GET.get('category')
        size_id = self.request.GET.get('size')
        filter_params = {}
        if category_id.isdigit():
            filter_params['drink__drink_type__category_id'] = category_id
        if size_id.isdigit():
            filter_params['drink__size_id'] = size_id
        return Order.objects.filter(**filter_params).order_by('id')

class OrderCreateView(generic.FormView):
    template_name = 'coffeeshop/index.html'
    form_class = OrderForm

def load_drinktypes(request):
    category_id = request.GET.get('category_id')
    if category_id.isdigit():
        drinktypes = DrinkType.objects.filter(category_id=category_id).order_by('name')
        # print(drinktypes)
        return render(request, 'coffeeshop/drinktype_dropdown_list_options.html', {'drinktypes': drinktypes})
    else:
        return HttpResponseBadRequest()

def load_sizes(request):
    drink_type_id = request.GET.get('drink_type_id')
    if drink_type_id.isdigit():
        sizes = set()
        for drink in Drink.objects.filter(drink_type_id=drink_type_id).select_related('size'):
        	sizes.add(drink.size)
        return render(request, 'coffeeshop/size_dropdown_list_options.html', {'sizes': sizes})
    else:
        return HttpResponseBadRequest()

def place_order(request):
    try:
        selected_drink = Drink.objects.filter(drink_type_id=request.POST['drink_type'], size_id=request.POST['size']).first()
        if selected_drink == None: raise Drink.DoesNotExist
    except (KeyError, Drink.DoesNotExist):
        # Redisplay the order form
        return render(request, 'coffeeshop/index.html', {
            'form': OrderForm(),
            'error_message': "Such selection is not available. Please make a new one.",
        })
    else:
        order = Order(quantity=request.POST['quantity'], drink=selected_drink, ordered_at=timezone.now())
        order.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('coffeeshop:order_list'))

coffeeshop/templates/coffeeshop/drinktype_dropdown_list_options.html
<option value="">Select</option>
{% for type in drinktypes %}
<option value="{{ type.pk }}">{{ type.name }}</option>
{% endfor %}

coffeeshop/templates/coffeeshop/filtered_order_list.html
{% extends "coffeeshop/order_table.html" %}

{% block content %}
<title>Shop Orders</title>
<h1>List of Filtered Orders</h1>
<p>
  <a href="{% url 'coffeeshop:order_list' %}">Back</a>
</p>
{% endblock %}

coffeeshop/templates/coffeeshop/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'coffeeshop/style.css' %}" />
<title>Coffee Shop</title>
<body onload="document.getElementById('order_form').reset();">
<h1>Welcome!</h1>
<p>Please place an order.</p>

{% if error_message %}<p style="color:red;"><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'coffeeshop:place_order' %}" method="post" id="order_form"
        data-drinktypes-url="{% url 'coffeeshop:ajax_load_drinktypes' %}"
        data-sizes-url="{% url 'coffeeshop:ajax_load_sizes' %}">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

<p><a href="{% url 'coffeeshop:order_list' %}">View All Orders</a></p>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$("#id_category").change(function () {
  var url = $("#order_form").attr("data-drinktypes-url");
  var catId = $(this).val();
  if (catId) {
    $.ajax({
      url: url,
      data: {
        'category_id': catId
      },
      success: function (data) {
        //console.log(data)
        $("#id_drink_type").html(data);
      }
    });
  } else $("#id_drink_type option:gt(0)").remove().end()
});

$("#id_drink_type").change(function () {
  var url = $("#order_form").attr("data-sizes-url");
  var typeId = $(this).val();
  if (typeId) {
    $.ajax({
      url: url,
      data: {
        'drink_type_id': typeId
      },
      success: function (data) {
        $("#id_size").html(data);
      }
    });
  } else $("#id_size option:gt(0)").remove().end()
});
</script>

coffeeshop/templates/coffeeshop/order_list.html
{% extends "coffeeshop/order_table.html" %}

{% block content %}
<title>Shop Orders</title>
<h1>List of Orders</h1>
<p>
  <a href="{% url 'coffeeshop:index' %}">Add New</a>
</p>

<p>Total Sales: {{ total_sales }}</p>

<form action="{% url 'coffeeshop:filtered_order_list' %}" method="get" id="filter_form">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Filter" />
</form>
{% endblock %}

coffeeshop/templates/coffeeshop/order_table.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'coffeeshop/style.css' %}" />

{% block content %}
{% endblock %}
<table border="1">
  <thead>
    <tr>
      <th>Index</th>
      <th>Drink Category</th>
      <th>Drink Name</th>
      <th>Size</th>
      <th>Quantity</th>
      <th>Unit Price($)</th>
      <th>Ordered At</th>
    </tr>
  </thead>
  <tbody>
    {% for order in order_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ order.drink.drink_type.category.name }}</td>
        <td>{{ order.drink.drink_type.name }}</td>
        <td>{{ order.drink.size.name }}</td>
        <td>{{ order.quantity }}</td>
        <td>{{ order.drink.price }}</td>
        <td>{{ order.ordered_at }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

coffeeshop/templates/coffeeshop/size_dropdown_list_options.html
<option value="">Select</option>
{% for size in sizes %}
<option value="{{ size.pk }}">{{ size.name }}</option>
{% endfor %}